HELLO WORLD
PrinceBadru/Hello-World pull request #1
Opened 2022-08-18 09:30 UTC by PrinceBadru

## Hello Microverse 
I accomplished 
- create a repository 
- Add HTML&CSS files

2022-08-18 10:00 UTC, HAMMAS-SALEEM requested changes
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/93039359/178569876-9fcda5e8-6819-4569-95ee-acb393903a05.jpg)

### Hey @PrinceBadru :wave:

### Highlights :1st_place_medal:
 
:heavy_check_mark: Meaningful commits
:heavy_check_mark: Added .gitignore
:heavy_check_mark: Following Github Flow

Good job on implementing some of the requirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional Suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @HAMMAS-SALEEM in your question so I can receive the notification. Otherwise reach out to me on slack which is more fast. You can reach out to me on slack by searching my name in **full-time-students** channel :+1:

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 10:00 UTC, HAMMAS-SALEEM commented on package.json
> +}
![pr-title](https://user-images.githubusercontent.com/93039359/185364413-077aacfc-3738-4cd4-9047-acd9a4a10eee.png)

- [ ] Your PR has a title that is not so descriptive enough. Because **HELLO WORD** is not describing what are you doing in the project. PR title fully describes what is happening in this branch. You could use **Setup Hello Microverse Project** for your PR title. :+1:

2022-08-18 10:00 UTC, HAMMAS-SALEEM commented on package.json
> +}
### Your Summary
![summary](https://user-images.githubusercontent.com/93039359/185365001-bd47b76d-f45d-4c30-bc1c-dc691f235ca9.png)

### Descriptive Summary Example :heavy_check_mark:
![good-summary](https://user-images.githubusercontent.com/93039359/184694824-ded06807-d049-4ad8-9971-cd9b9d4143c0.png)


- [ ] You don't have a descriptive summary for your project. You can see the image above to get an idea of what a descriptive summary looks like. The summary tells in detail what are you doing in this pull request and why. :thinking:

2022-08-18 10:00 UTC, HAMMAS-SALEEM commented on package.json
> +}
### Your branch name
![pr-title (copy)](https://user-images.githubusercontent.com/93039359/185365366-92463120-c92b-4275-ae38-506dab9222cf.png)

- [ ] Your branch name is not descriptive enough. You are using **feature**, you can use  **feature/setup-hello-microverse** :+1: which is more descriptive and shows your professionlism with your project :blush:

2022-08-18 10:00 UTC, HAMMAS-SALEEM commented on package.json
> +}
### Your Readme
![readme-part1 (copy)](https://user-images.githubusercontent.com/93039359/185366740-e136ae48-8e53-4a29-b46e-f540b2d14546.png)
![readme-part2 (copy)](https://user-images.githubusercontent.com/93039359/185366754-4159eeea-fde4-40bd-95cc-fb8727e476a7.png)

- [ ] Please add the missing things in your readme file. This is your documentation file for this project so please take it seriously :thinking: You can use this [sample](https://github.com/HAMMAS-SALEEM/Hello-Microverse/blob/refactor-authentication/README.md) to get a good idea :+1:

2022-08-18 10:00 UTC, HAMMAS-SALEEM commented on package.json
> +}
### Your MIT link
![mit-link](https://user-images.githubusercontent.com/93039359/185367250-edfb3417-a84f-4415-ac2a-b0773299e2ca.png)

- [ ] Your link is broken. Please replace `./LICENSE` with `./MIT.md` to make your link work :blush:

2022-08-18 10:00 UTC, HAMMAS-SALEEM commented on package.json
> +}
### Your MIT file
![MIT-file (copy)](https://user-images.githubusercontent.com/93039359/185368176-5640e227-c6a2-4da0-8095-80b9537caa8a.png)


- [ ] Your MIT file is missing your name, current year, and app type. This is the license file of your project so please take it seriously :thinking: you can use this [sample](https://github.com/HAMMAS-SALEEM/Hello-Microverse/blob/refactor-authentication/MIT.md) to get a good idea :+1:

2022-08-22 16:27 UTC, danmainah requested changes
Hi @PrinceBadru,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights


# Required Changes ♻️

- [ ] Kindly add a descriptive pull request title eg setup Hello World project, it should indicate changes in the pull request.

- [ ] Kindly ensure your readme file is customized currently you have a microverse template that is not customized.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-08-23 08:27 UTC, prolajumokeoni approved these changes
Hi @PrinceBadru 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- No linter errors ✅ 
- Github flow was used correctly 🚀 
- Good Pr title and description 💪🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] Branch name should have a name of a feature or action related to your project eg. “hello-microverse” or “setup-project”



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-23 17:39 UTC, merged